# Email address to use in the 'from' field for emails sent by Kochiku.
sender_email_address: 'kochiku@example.com'

# Email address where kochiku should send problems with the build system (for example, errors),
# as distinct from failures in a particular test (which go to the people who committed code).
kochiku_notifications_email_address: 'kochiku-notifications@example.com'

# Domain name to use in constructing generic addresses. For example noreply@example.com in git commits.
domain_name: 'example.com'

# Set to true if Kochiku is served over https
use_https: false

# Host name where Kochiku is serving web pages.
kochiku_host: 'kochiku.example.com'

# If you would like Kochiku to clone and fetch repositories from a git mirror
# uncomment this setting and fill in the url to your mirror.
# git_mirror: 'git://git-mirror.example.com/'
